apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: default         
  labels:
    release: monitoring       
spec:
  selector:
    matchLabels:
      app: backend            
  endpoints:
    - port: "5000"            
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default