apiVersion: batch/v1
kind: CronJob
metadata:
  name: api-ping-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ping-worker
            image: busybox
            command:
            - /bin/sh
            - -c
            - "wget -qO- http://backend-service:5000/health"
          restartPolicy: OnFailure
