name: Continuous Integration (CI)

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
      
permissions:
  contents: read

jobs:

  CI-Validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform Format & Validation
        run: |
          cd terraform
          terraform init -backend=false
          terraform validate
          terraform fmt -check

      - name: Setup Helm
        uses: azure/setup-helm@v4
      - name: Lint Helm Chart Manifests
        run: helm lint ./helm/myapp

      - name: Save Manifests as Pipeline Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: verified-helm-chart
          path: ./helm/myapp

  # Container-Security-Scan-Frontend:
  #   uses: clouddrove/github-shared-workflows/.github/workflows/docker-scanner.yml@master
  #   with:
  #     severity: 'CRITICAL,HIGH'
  #     dockerfile-path: ./frontend.Dockerfile

  # Container-Security-Scan-Backend:
  #   uses: clouddrove/github-shared-workflows/.github/workflows/docker-scanner.yml@master
  #   with:
  #     severity: 'CRITICAL,HIGH'
  #     dockerfile-path: ./backend.Dockerfile
